"""initial schema

Revision ID: c24b345eeea9
Revises: 
Create Date: 2026-09-10 22:10:37.833814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24b345eeea9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.Enum('ACTION_REQUIRED', 'WARNING', 'RISK', 'FINANCIAL', 'SYSTEM', 'INFORMATION', name='notificationseverity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_href', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pr_number', sa.String(length=30), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('part_code', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('application', sa.String(length=200), nullable=True),
    sa.Column('drawing_reference', sa.String(length=100), nullable=True),
    sa.Column('drawing_revision_available', sa.Boolean(), nullable=False),
    sa.Column('required_date', sa.Date(), nullable=False),
    sa.Column('requesting_department', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'VALIDATING', 'READY_FOR_SOURCING', 'RFQ_IN_PROGRESS', 'RESPONSES_RECEIVED', 'ANALYSIS_READY', 'AWAITING_APPROVAL', 'APPROVED', 'PO_CREATED', 'FULFILLMENT', 'COMPLETED', name='prstatus'), nullable=False),
    sa.Column('exceptions', sa.JSON(), nullable=False),
    sa.Column('estimated_value_amount', sa.Float(), nullable=True),
    sa.Column('estimated_value_currency', sa.String(length=3), nullable=True),
    sa.Column('has_been_analyzed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisitions_pr_number'), 'requisitions', ['pr_number'], unique=True)
    op.create_index(op.f('ix_requisitions_status'), 'requisitions', ['status'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('approval_status', sa.Enum('APPROVED', 'PENDING_APPROVAL', 'SUSPENDED', name='supplierapprovalstatus'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Float(), nullable=True),
    sa.Column('quality_acceptance_rate', sa.Float(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('average_unit_price_amount', sa.Float(), nullable=True),
    sa.Column('average_unit_price_currency', sa.String(length=3), nullable=True),
    sa.Column('total_purchases', sa.Integer(), nullable=False),
    sa.Column('sample_size_units', sa.Integer(), nullable=True),
    sa.Column('sample_size_transactions', sa.Integer(), nullable=False),
    sa.Column('performance_measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_overall', sa.Float(), nullable=True),
    sa.Column('score_price', sa.Float(), nullable=True),
    sa.Column('score_quality', sa.Float(), nullable=True),
    sa.Column('score_delivery', sa.Float(), nullable=True),
    sa.Column('score_commercial', sa.Float(), nullable=True),
    sa.Column('score_config_version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requisition_id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.Enum('REQUIREMENT_AGENT', 'SUPPLIER_INTELLIGENCE_AGENT', 'COMMUNICATION_AGENT', 'QUOTE_INTELLIGENCE_AGENT', 'PROCUREMENT_ANALYST', 'RISK_AGENT', 'NEGOTIATION_AGENT', name='agentkind'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'ANALYZING', 'WAITING_FOR_EXTERNAL_EVENT', 'WAITING_FOR_REVIEW', 'COMPLETED', 'FAILED', name='agentrunstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('output_href', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_requisition_id'), 'agent_runs', ['requisition_id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requisition_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_band', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT_DATA', name='confidenceband'), nullable=False),
    sa.Column('recommendation_state', sa.Enum('READY', 'REVIEW_REQUIRED', 'INSUFFICIENT_DATA', name='recommendationstate'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('trade_off', sa.Text(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('policy_checks', sa.JSON(), nullable=False),
    sa.Column('alternatives', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_requisition_id'), 'ai_recommendations', ['requisition_id'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('requisition_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'ACKNOWLEDGED', 'DISPATCHED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CLOSED', name='postatus'), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('subtotal_amount', sa.Float(), nullable=False),
    sa.Column('freight_amount', sa.Float(), nullable=False),
    sa.Column('tax_rate_percent', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('validation_checks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_requisition_id'), 'purchase_orders', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_reference', sa.String(length=30), nullable=False),
    sa.Column('requisition_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('source_document_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price_amount', sa.Float(), nullable=False),
    sa.Column('unit_price_currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('freight_amount', sa.Float(), nullable=False),
    sa.Column('freight_currency', sa.String(length=3), nullable=False),
    sa.Column('tax_rate_percent', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('extracted_fields', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.Enum('VALID', 'NEEDS_REVIEW', 'INVALID', name='quotevalidationstatus'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_quote_reference'), 'quotes', ['quote_reference'], unique=True)
    op.create_index(op.f('ix_quotes_requisition_id'), 'quotes', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_quotes_supplier_id'), 'quotes', ['supplier_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfq_number', sa.String(length=30), nullable=False),
    sa.Column('requisition_id', sa.String(length=36), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfqs_requisition_id'), 'rfqs', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_rfqs_rfq_number'), 'rfqs', ['rfq_number'], unique=True)
    op.create_table('supplier_price_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('unit_price_amount', sa.Float(), nullable=False),
    sa.Column('unit_price_currency', sa.String(length=3), nullable=False),
    sa.Column('po_reference', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_price_history_supplier_id'), 'supplier_price_history', ['supplier_id'], unique=False)
    op.create_table('supplier_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('po_reference', sa.String(length=30), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('unit_price_amount', sa.Float(), nullable=False),
    sa.Column('unit_price_currency', sa.String(length=3), nullable=False),
    sa.Column('delivered_on_time', sa.Boolean(), nullable=False),
    sa.Column('quality_accepted', sa.Boolean(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_transactions_supplier_id'), 'supplier_transactions', ['supplier_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('BUYER', 'PURCHASE_MANAGER', 'SUPPLIER', 'IT_ADMIN', 'AUDITOR', name='actorrole'), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('EXPECTED', 'AT_RISK', 'DISPATCHED', 'PARTIAL', 'RECEIVED', name='deliverystatus'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('last_supplier_communication_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_purchase_order_id'), 'deliveries', ['purchase_order_id'], unique=True)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_table('po_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_amount', sa.Float(), nullable=False),
    sa.Column('unit_price_currency', sa.String(length=3), nullable=False),
    sa.Column('line_value_amount', sa.Float(), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_line_items_purchase_order_id'), 'po_line_items', ['purchase_order_id'], unique=False)
    op.create_table('rfq_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'OPENED', 'RESPONDED', 'PARTIAL', 'NO_RESPONSE', 'ESCALATED', name='rfqrecipientstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminders_sent', sa.Integer(), nullable=False),
    sa.Column('extracted_fields', sa.JSON(), nullable=False),
    sa.Column('completeness', sa.Enum('COMPLETE', 'PARTIAL', 'AWAITING', name='responsecompleteness'), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_recipients_rfq_id'), 'rfq_recipients', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_rfq_recipients_supplier_id'), 'rfq_recipients', ['supplier_id'], unique=False)
    op.create_table('communication_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.Enum('ELECON', 'SUPPLIER', 'AI_DRAFT', name='messagesender'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['rfq_recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_messages_recipient_id'), 'communication_messages', ['recipient_id'], unique=False)
    op.create_table('delivery_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('delivery_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suggested_action_label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_exceptions_delivery_id'), 'delivery_exceptions', ['delivery_id'], unique=False)
    op.create_table('delivery_timeline_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('delivery_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.Enum('PO_APPROVED', 'PO_SENT', 'ACKNOWLEDGED', 'DISPATCHED', 'DELIVERED', name='deliverytimelinekey'), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_timeline_steps_delivery_id'), 'delivery_timeline_steps', ['delivery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_timeline_steps_delivery_id'), table_name='delivery_timeline_steps')
    op.drop_table('delivery_timeline_steps')
    op.drop_index(op.f('ix_delivery_exceptions_delivery_id'), table_name='delivery_exceptions')
    op.drop_table('delivery_exceptions')
    op.drop_index(op.f('ix_communication_messages_recipient_id'), table_name='communication_messages')
    op.drop_table('communication_messages')
    op.drop_index(op.f('ix_rfq_recipients_supplier_id'), table_name='rfq_recipients')
    op.drop_index(op.f('ix_rfq_recipients_rfq_id'), table_name='rfq_recipients')
    op.drop_table('rfq_recipients')
    op.drop_index(op.f('ix_po_line_items_purchase_order_id'), table_name='po_line_items')
    op.drop_table('po_line_items')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_purchase_order_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_table('users')
    op.drop_index(op.f('ix_supplier_transactions_supplier_id'), table_name='supplier_transactions')
    op.drop_table('supplier_transactions')
    op.drop_index(op.f('ix_supplier_price_history_supplier_id'), table_name='supplier_price_history')
    op.drop_table('supplier_price_history')
    op.drop_index(op.f('ix_rfqs_rfq_number'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_requisition_id'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_quotes_supplier_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_requisition_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_reference'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_requisition_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_ai_recommendations_requisition_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_agent_runs_requisition_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_requisitions_status'), table_name='requisitions')
    op.drop_index(op.f('ix_requisitions_pr_number'), table_name='requisitions')
    op.drop_table('requisitions')
    op.drop_table('notifications')
    # ### end Alembic commands ###
